[package]
name = "borg-timemachine"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
chrono = "0.4"
clap = { version = "4.4", features = ["derive"] }

[dev-dependencies]
pretty_assertions = "1.4.0"
tempfile = "3.8"
